--------------------------------------------------------
--  파일이 생성됨 - 월요일-1월-22-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"COLUMN2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "PROJECT"."EMP" 
   (	"EMPNO" NUMBER(8,0), 
	"DEPTNO" NUMBER(3,0), 
	"POSITION" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"SAL" NUMBER(20,0), 
	"HIREDATE" DATE, 
	"JUMIN" NUMBER(13,0), 
	"TEL" NUMBER(11,0), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"ACCOUNT" NUMBER(20,0), 
	"FIRSTNAME" VARCHAR2(10 BYTE), 
	"LASTNAME" VARCHAR2(10 BYTE), 
	"PROFILEIMAGE" VARCHAR2(40 BYTE) DEFAULT 'default.jpg'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERINFO
--------------------------------------------------------

  CREATE TABLE "PROJECT"."USERINFO" 
   (	"EMPNO" NUMBER(8,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TEL" VARCHAR2(12 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."DEPT_PK" ON "PROJECT"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."PK_EMPNO" ON "PROJECT"."EMP" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UC_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."UC_NAME" ON "PROJECT"."EMP" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."DEPT" ADD CONSTRAINT "DEPT_PK" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."DEPT" MODIFY ("DEPTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "PROJECT"."EMP" ADD CONSTRAINT "UC_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."EMP" MODIFY ("PROFILEIMAGE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."EMP" ADD CONSTRAINT "PK_EMPNO" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."EMP" MODIFY ("DEPTNO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERINFO
--------------------------------------------------------

  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."USERINFO" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "PROJECT"."EMP" ADD CONSTRAINT "EMP_FK1" FOREIGN KEY ("DEPTNO")
	  REFERENCES "PROJECT"."DEPT" ("DEPTNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERINFO
--------------------------------------------------------

  ALTER TABLE "PROJECT"."USERINFO" ADD CONSTRAINT "USERINFO_FK1" FOREIGN KEY ("EMPNO")
	  REFERENCES "PROJECT"."EMP" ("EMPNO") ENABLE;
  ALTER TABLE "PROJECT"."USERINFO" ADD CONSTRAINT "USERINFO_FK2" FOREIGN KEY ("NAME")
	  REFERENCES "PROJECT"."EMP" ("NAME") ENABLE;
